create table line
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    color         varchar(255),
    deleted       boolean,
    name          varchar(255),
    primary key (id)
);

alter table line
    add constraint UK_9ney9davbulf79nmn9vg6k7tn unique (name);


create table station
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    name          varchar(255),
    primary key (id)
);

alter table station
    add constraint UK_gnneuc0peq2qi08yftdjhy7ok unique (name);