create table line
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    color         varchar(255),
    deleted       boolean,
    name          varchar(255),
    primary key (id)
);

create table section
(
    id              bigint generated by default as identity,
    deleted         boolean,
    distance        integer,
    line_id         bigint not null,
    next_station_id bigint,
    station_id      bigint not null,
    primary key (id)
);

create table station
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    deleted       boolean,
    name          varchar(255),
    primary key (id)
);

alter table line
    add constraint UK_9ney9davbulf79nmn9vg6k7tn unique (name);

alter table station
    add constraint UK_gnneuc0peq2qi08yftdjhy7ok unique (name);

alter table section
    add constraint fk_line_station_to_line
        foreign key (line_id)
            references line;

alter table section
    add constraint fk_section_to_next_station
        foreign key (next_station_id)
            references station;

alter table section
    add constraint fk_section_to_station
        foreign key (station_id)
            references station;