create table line
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    color         varchar(255),
    deleted       boolean,
    name          varchar(255),
    primary key (id)
);

create table line_station
(
    id              bigint generated by default as identity,
    deleted         boolean,
    distance        integer,
    next_station_id bigint,
    station_id      bigint not null,
    line_id         bigint not null,
    primary key (id)
);

create table station
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    deleted       boolean,
    name          varchar(255),
    primary key (id)
);

alter table line
    add constraint UK_9ney9davbulf79nmn9vg6k7tn unique (name);

alter table station
    add constraint UK_gnneuc0peq2qi08yftdjhy7ok unique (name);

alter table line_station
    add constraint FKawlxkihpbfvr39jka1t9jbbxu
        foreign key (line_id)
            references line;