INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (1, '강남역', now(), now());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (2, '양재역', now(), now());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (3, '신림역', now(), now());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (4, '서원역', now(), now());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (5, '양재시민의숲역', now(), now());

