INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (1, '지하철역이름', SYSDATE(), SYSDATE());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (2, '새로운지하철역이름', SYSDATE(), SYSDATE());
INSERT INTO STATION (ID, NAME, CREATED_DATE, MODIFIED_DATE) VALUES (3, '또다른지하철역이름', SYSDATE(), SYSDATE());
